In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

In [20]:
df = pd.read_csv("../data/processed/reddit_posts_cleaned.csv")

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1782 entries, 0 to 1781
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   keyword       1782 non-null   object
 1   title         1782 non-null   object
 2   subreddit     1782 non-null   object
 3   timestamp     1782 non-null   object
 4   post_url      1782 non-null   object
 5   scrape_date   1607 non-null   object
 6   batch_number  1607 non-null   float64
 7   source        1607 non-null   object
dtypes: float64(1), object(7)
memory usage: 111.5+ KB

In [22]:
df.head()

,keyword,title,subreddit,timestamp,post_url,scrape_date,batch_number,source
0,developersindia hiring,How's Infosys for starters 😳,r/IndiaTech,2026-03-10T07:42:32+00:00,https://old.reddit.com/r/IndiaTech/comments/1r...,NaN,NaN,NaN
1,developersindia hiring,Who's hiring? - Monthly Megathread - June 2026,r/developersIndia,2026-06-01T04:32:05+00:00,https://old.reddit.com/r/developersIndia/comme...,NaN,NaN,NaN
2,developersindia hiring,Who's hiring? - Monthly Megathread - February ...,r/developersIndia,2026-02-01T04:32:29+00:00,https://old.reddit.com/r/developersIndia/comme...,NaN,NaN,NaN
3,developersindia hiring,Who's looking for work? - Monthly Megathread -...,r/developersIndia,2026-06-01T04:30:14+00:00,https://old.reddit.com/r/developersIndia/comme...,NaN,NaN,NaN
4,developersindia hiring,Who's hiring? - Monthly Megathread - May 2026,r/developersIndia,2026-05-01T04:32:13+00:00,https://old.reddit.com/r/developersIndia/comme...,NaN,NaN,NaN

In [23]:
df.describe(include="all")

,keyword,title,subreddit,timestamp,post_url,scrape_date,batch_number,source
count,1782,1782,1782,1782,1782,1607,1607.000000,1607
unique,91,1672,569,1782,1782,1,NaN,1
top,fresher jobs india,[For Hire] [Remote] [India] - Full stack web/a...,r/developersIndia,2026-06-27T17:27:54+00:00,https://old.reddit.com/r/jobhuntify/comments/1...,2026-07-01,NaN,reddit
freq,23,12,200,1,1,1607,NaN,1607
mean,NaN,NaN,NaN,NaN,NaN,NaN,2.863721,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,1.323971,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN

In [24]:
df.isnull().sum()

keyword           0
title             0
subreddit         0
timestamp         0
post_url          0
scrape_date     175
batch_number    175
source          175
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.shape

(1782, 8)

In [27]:
df.nunique()

keyword           91
title           1672
subreddit        569
timestamp       1782
post_url        1782
scrape_date        1
batch_number       5
source             1
dtype: int64